baseURL = "https://blog.dcjanus.com"
defaultContentLanguage = "zh-cn"
languageCode = "zh-CN"
hasCJKLanguage = true
title = "DCjanus 的博客"
theme = "DoIt"
enableEmoji = true

[params]
  version = "0.3.X"
  gitRepo = "https://github.com/dcjanus/dcjanus.github.io"

[params.author]
  name = "DCjanus"
  email = "dcjanus@dcjanus.com"
  link = "https://github.com/dcjanus"
  gravatarEmail = "dcjanus@dcjanus.com"

[params.rss]
  rss = 10

[params.home.profile]
  enable = true
  gravatarEmail = "dcjanus@dcjanus.com"
  title = "DCjanus 的博客"
  typeit = false
  social = true

[params.footer]
  author = true

[taxonomies]
  author = "authors"
  category = "categories"
  tag = "tags"
  series = "series"

[params.social]
  GitHub = "dcjanus"
  Email = "DCjanus@dcjanus.com"

[params.page.outdatedArticleReminder]
  enable = false

[params.page.comment]
  enable = true
  [params.page.comment.utterances]
    enable = true
    repo = "DCjanus/dcjanus.github.io"
    issueTerm = "pathname"
    label = "comment"
    lightTheme = "github-light"
    darkTheme = "github-dark"

[[menu.main]]
  identifier = "posts"
  name = "文章"
  url = "/posts/"
  weight = 1
[[menu.main]]
  identifier = "tags"
  name = "标签"
  url = "/tags/"
  weight = 2
[[menu.main]]
  identifier = "rss"
  name = "订阅"
  url = "/index.xml"
  weight = 4
[[menu.main]]
  identifier = "authors"
  name = "作者"
  url = "/authors/"
  weight = 5
[[menu.main]]
  identifier = "github"
  post = ""
  name = "源码"
  url = "https://github.com/dcjanus/dcjanus.github.io"
  title = "GitHub"
  weight = 9
[markup]
  [markup.highlight]
    noClasses = false
