baseURL = "https://blog.dcjanus.com"
defaultContentLanguage = "zh-cn"
languageCode = "zh-CN"
hasCJKLanguage = true
title = "DCjanus 的博客"
theme = "DoIt"

[params]
  version = "0.2.X"
  gitRepo = "https://github.com/dcjanus/dcjanus.github.io"

[params.rss]
  rss = 10

[params.home.profile]
  enable = true
  gravatarEmail = "dcjanus@dcjanus.com"
  title = "DCjanus 的博客"
  typeit = false
  social = true

[params.social]
  GitHub = "dcjanus"

[params.page.outdatedArticleReminder]
  enable = false

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 3
  [[menu.main]]
    identifier = "rss"
    name = "订阅"
    url = "/index.xml"
    weight = 4

[markup]
  [markup.highlight]
    noClasses = false